### ISSUE TITLE
pyarrow 5.0 support?

### ISSUE THREAD

**Issue by ldacey** [blue-yonder/turbodbc#318]
```
name: pyarrow
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pyarrow=5
  - turbodbc
```

I removed all other packages and tried to narrow down what was causing conflicts when trying to update pyarrow to 5.0, and it seems like it is turbodbc. Can this be updated on conda-forge by chance?

**Comment by xhochy** [comment]
Please make a PR to the feedstock on conda-forge and add 5.0 to the conda_build_config.yaml

**Comment by ldacey** [comment]
Sorry, I have not tried this before. 

I checked https://github.com/conda-forge/turbodbc-feedstock but it seems like all of the commits are mostly automated. I did not see a file name conda_build_config.yaml. I see a conda-forge.yml file but it does not look like it indicates the pyarrow version, so I must be missing something.

```
build_platform:
  osx_arm64: osx_64
provider:
  win: azure
test_on_native_only: true
conda_forge_output_validation: true
```

I see an example pull request to bump pyarrow version here (updated setup.py) which I was thinking of using as a reference:
https://github.com/blue-yonder/turbodbc/pull/308 

Would I update the setup.py / CHANGELOG to include pyarrow 5.0?
