### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by tzipperle** [blue-yonder/turbodbc#332]
Hi,

I have installed turbodbc with conda-forge in and following environment:

```yaml
name: turobdc
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - pyarrow
  - turbodbc
  - pyodbc
```

```python
 
 con_options = turbodbc.make_options(
     prefer_unicode=True,
     limit_varchar_results_to_max=True
 )

 connection = turbodbc.connect(
     connection_string='string',
     turbodbc_options=con_options
 )

cursor = conn.cursor()
cursor.execute('SELECT ...')

df = cursor.fetchallarrow().to_pandas() # here crash python
```

When I excute the `cursor.fetchallarrow()` my python process crash with `Process finished with exit code -1073741819 (0xC0000005)`. This error occurs with all fetch functions.

I have tested the odbc with pyodbc and this package works fine.

Have you any idea whats going wrong?

Thomas
